Add generate_1khz_wave.py
Since wenwen_generate_1khz_wave.py runing failed with following failure,
add this new one.
AttributeError: 'numpy.ndarray' object has no attribute 'tostring'